name: Hello CI
on:
  push:
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Say Hello
      run: echo "CI esta funcionando"

    - name: Show runner info
      run: |
        echo "Runner OS: $RUNNER_OS"
        uname -a
